server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:          
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/insta?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: insta
    password: bitc5600
    
  jpa:
    open-in-view: true #db connection을 view단 까지 오픈해줌 그래서 lazy loading을 가능하게 해준다.
    hibernate:
      ddl-auto: update #update create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
   
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      
  security:
    user:
      name: cos
      password: 1234   

cos: #변수임
  secret: 겟인데어 #자바에서 가져다 쓸 수 있음

file:
  path: C:/src/springwork/instargram/src/main/resources/upload/
